name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      # Runs a single command using the runners shell
      - run: |
          update-alternatives --all --skip-auto
